name: NodeJS with Webpack

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: |
        npm install --force
      
    - name: Build
      run: |
        npm run build
        
    - name: deploy
    - uses: ad-m/github-push-action@gh-pages
      with: 
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        branch: "gh-pages"
